# Generated by Django 3.2.2 on 2021-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210517_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
